[project]
name = "odoo-addons-oca-sale-reporting"
version = "18.0.20250205.0"
dependencies = [
    "odoo-addon-sale_order_line_position==18.0.*",
    "odoo-addon-sale_report_delivered==18.0.*",
    "odoo-addon-sale_report_salesperson_from_partner==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
