[project]
name = "odoo-addons-oca-sale-reporting"
version = "18.0.20241220.0"
dependencies = [
    "odoo-addon-sale_order_line_position==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
